[rendered-link]
trigger-files = ["src/"]

[assign]

[notify-zulip."I-types-nominated"]
zulip_stream = 326866 # #T-types/nominated
topic = "goals#{number}: {title}"
message_on_add = """\
@*T-types* goals#{number} "{title}" has been nominated for team discussion.
"""
github_comment = "A [#t-types/nominated topic]({zulip_topic_url}) was opened to discuss this issue."
message_on_remove = "goals#{number}'s nomination has been removed. Thanks all for participating!"
message_on_close = "goals#{number} has been closed. Thanks for participating!"
message_on_reopen = "goals#{number} has been reopened. Pinging @*T-types*."


[notify-zulip."C-goal-proposal"]
zulip_stream = 546987 # #goals/proposed
topic = "goals#{number}: {title}"
message_on_add = """\
New goal proposal: "{title}" (goals#{number}).

cc {recipients}
"""
github_comment = "A [#goals/proposed topic]({zulip_topic_url}) was opened to discuss this issue."
message_on_close = "goals#{number} has been resolved. Thanks for participating!"


[notify-zulip."I-goals-nominated"]
zulip_stream = 478266 # #goals/meta
topic = "goals#{number}: {title}"
message_on_add = """\
Nominated issue: "{title}" (goals#{number}).

cc {recipients}
"""
github_comment = "A [#goals/meta topic]({zulip_topic_url}) was opened to discuss this issue."
message_on_close = "goals#{number} has been resolved. Thanks for participating!"
message_on_reopen = "@*T-goals*, goals#{number} has been reopened."
